import { User } from "./interfaces";

export const getUserTesting = (): User => {
  return {
    id: "601803a13db4900043735668",
    email: "countergank.ti@gmail.com",
    nick: "countergank",
    username: "countergank",
    avatarId: "9e46410eb9f4f85db6dadce1024a1ded25.png",
    configs: [
      {
        name: "offline",
        value: "1",
      },
    ],
    firstName: "Countergank",
    lastName: "TI",
    specialGroups: [],
    fullName: "Countergank TI",
    company: {
      id: "5e8b6d1fb784120043344cf9",
      name: "Proguide",
    },
    groups: [
      {
        id: "5e8b6d66b784120043344d06",
        name: "Software Factory CdelU",
      },
    ],
    allRoles: [
      {
        appId: "5e726d850965870030a57956",
        appName: "modulobpm",
        permissions: [
          {
            element: "Todos los Elementos",
            componentId: "5e726d850965870030a57957",
            permission: true,
            componentName: "Todos los Componentes",
          },
        ],
        name: "Nombre de Rol",
        id: "60ef4cc94a0ba800433e4212",
      },
    ],
    applications: [
      {
        id: "5eab82b25ddbba002e184dc4",
        name: "modulodashboard",
        baseUrl: "https://dashboard.dev.countergank.com",
        url: "https://dashboard.dev.countergank.com/auth",
        permission: "",
        order: 1,
        config: {
          target: "_self",
          includeToken: true,
          params: "/",
        },
        title: "Tablero",
        icon: "DesktopWindows",
      },
      {
        id: "5eab80a575cb408761c3728f",
        name: "moduloadmin",
        url: "",
        baseUrl: "https://beepmpportal.dev.countergank.com",
        title: "Administrador",
        permission: "",
        order: 9,
        description: "",
        default: false,

        image: "",
        childrens: [
          {
            id: "610c42ee82efce8b8322dd11",
            name: "usuarios",
            url: "https://beepmpportal.dev.countergank.com/auth",
            permission: "",
            order: 1,
            config: {
              target: "_self",
              includeToken: true,
              adapt: true,
              params: "/administrator/usuarios",
            },
            title: "Usuarios",
            default: false,
          },
          {
            id: "610c430c82efce8b8322dde1",
            name: "grupousuarios",
            permission: "",
            order: 2,
            url: "https://beepmpportal.dev.countergank.com/auth",
            config: {
              target: "_self",
              includeToken: true,
              adapt: true,
              params: "/administrator/grupousuarios",
            },
            title: "Grupos de Usuarios",
            default: false,
          },
          {
            id: "610c432b82efce8b8322ded0",
            name: "roles",
            permission: "",
            order: 3,
            url: "https://beepmpportal.dev.countergank.com/auth",
            config: {
              target: "_self",
              includeToken: true,
              adapt: true,
              params: "/administrator/roles",
            },
            title: "Roles de Usuarios",
            default: false,
          },
          {
            id: "611810f382efce8b837f6a68",
            name: "empresas",
            url: "https://beepmpportal.dev.countergank.com/auth",
            permission: "",
            order: 4,
            config: {
              target: "_self",
              includeToken: true,
              adapt: true,
              params: "/administrator/empresas",
            },
            title: "Empresas",
            default: false,
          },
          {
            id: "611810f382efce8b837f6a76",
            name: "notificaciones",
            url: "https://beepmpportal.dev.countergank.com/auth",
            permission: "",
            order: 6,
            config: {
              target: "_self",
              includeToken: true,
              adapt: true,
              params: "/administrator/notificaciones",
            },
            title: "Notificaciones",
            default: false,
          },
          {
            id: "611810f382efce8b837f6a7d",
            name: "auditory",
            url: "https://beepmpportal.dev.countergank.com/auth",
            permission: "",
            order: 7,
            config: {
              target: "_self",
              includeToken: true,
              adapt: true,
              params: "/administrator/auditoria",
            },
            title: "Auditoría de Logins",
            default: false,
          },
          {
            id: "611810f382efce8b837f6a83",
            name: "widgets",
            url: "https://beepmpportal.dev.countergank.com/auth",
            permission: "",
            order: 8,
            config: {
              target: "_self",
              includeToken: true,
              adapt: true,
              params: "/administrator/widgets",
            },
            title: "Widgets Y Reportes",
            default: false,
          },
        ],
      },
    ],
    filters: [
      {
        id: "6043cb739a758bdac03ab123",
        appId: "5e726d850965870030a57956",
        appName: "Workflow",
        fields: [
          {
            name: "hiddenanio",
            type: "number",
            caption: "Año",
            defaultValue: "",
            multiple: false,
            values: [],
          },
          {
            name: "numberid",
            type: "number",
            caption: "Id.Caso",
            defaultValue: "",
            multiple: false,
            values: [],
          },
          {
            name: "usuario",
            type: "enum",
            caption: "Usuario Responsable",
            defaultValue: "",
            multiple: false,
            values: {
              url: "{INTEGRATION_URL}:{INTEGRATION_PORT}/usuarios?groups=all",
              fixedItems: [
                {
                  id: "",
                  name: "Todos los usuarios",
                },
              ],
              fieldnames: {
                id: "username",
                name: "fullName",
              },
            },
          },
          {
            name: "referenciavalor",
            type: "text",
            caption: "Referencia",
            defaultValue: "",
            multiple: false,
            values: [],
          },
        ],
      },
    ],
  };
};
